#Spring properties
#Service registers under this name
#spring:
#  application:
#    name: NoteMicroservice
#
##Discovery Server Access
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
# HTTP Server (Tomcat) Port
#server: 
#  port: 8763
#
#Disable Spring Boot's "Whitelabel" default error page, so we can use our own
#error:
#  whitelabel:
#    enabled: false
